<?php

namespace App\Crawler\Sites\Resource;

use App\Crawler\Sites\SiteAbstract;
use Symfony\Component\DomCrawler\Crawler as DomCrawler;

class Job123 extends SiteAbstract
{
    public function startUrls(): array
    {
        // TODO: Implement startUrls() method.
        return ['https://123job.vn'];
    }

    public function shouldCrawl(string $url)
    {
        return preg_match("/^https:\/\/123job\.vn\/(viec-lam|việc-làm|vi%E1%BB%87c-l%C3%A0m)/", $url);
    }

    public function shouldGetData(string $url)
    {
        return preg_match("/^https:\/\/123job\.vn\/viec-lam/", $url);
    }

    public function getInfoFromCrawler(DomCrawler $dom_crawler, string $url = '')
    {
        return parent::getInfoFromCrawler($dom_crawler, $url); // TODO: Change the autogenerated stub
    }
}
